### ISSUE TITLE
Feature request: Add parameters for outside config

### ISSUE THREAD

**Issue by kabatak** [middlewares/shutdown#2]
Would be nice if could do something like `new Middlewares\Shutdown($isShutdown)` so that if `$isShutdown === true` then it will execute, if false, does nothing.

This way users can configure `$isShutdown` wherever in their own config files.

**Comment by oscarotero** [comment]
Why don't use a simple `if` on create the dispatcher?
```php
$middlewares = [];

if ($isShutdown) {
    $middlewares[] = new Middlewares\Shutdown();
}

$dispatcher = new Dispatcher($middlewares);
```
So you don't have to instantiate a middleware that is not going to be used.
Other option is use something like this: https://github.com/northwoods/conditional-middleware

**Comment by kabatak** [comment]
You're right. That's faster.
